[package]

name = "claxon"
version = "0.2.1"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "A FLAC decoding library"
keywords = ["flac", "lossless", "audio", "codec"]
license = "Apache-2.0"
readme = "readme.md"
homepage = "https://github.com/ruuda/claxon#readme"
repository = "https://github.com/ruuda/claxon"
documentation = "https://docs.rs/claxon"

[dev-dependencies]

hound = { git = "https://github.com/ruuda/hound", rev = "2b212bf" }
time = "0.1.35"
