[package]

name = "claxon"
version = "0.1.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "A FLAC decoding library"
keywords = ["flac", "lossless", "audio", "codec"]
license = "Apache-2.0"
readme = "readme.md"
homepage = "https://github.com/ruuda/claxon"
repository = "https://github.com/ruuda/claxon"

[dev-dependencies]

hound = "1.1.0"
