[package]

name = "snow"
version = "0.0.1"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]
description = "A FLAC decoding library"
keywords = ["flac", "lossless", "audio", "codec"]
license = "GPL-3.0+"
readme = "readme.md"
