[package]
name = "claxon-fuzz"
version = "0.0.0"
authors = ["Ruud van Asseldonk <dev@veniogames.com>"]

[dependencies.claxon]
path = ".."

[[bin]]
name = "decode-full"
path = "fuzzers/decode_full.rs"
